#!/usr/bin/zsh


DESK='/Data/_'

echo "
XDG_DESKTOP_DIR='$DESK'
XDG_DOWNLOAD_DIR='$DESK'
XDG_TEMPLATES_DIR='$DESK'
XDG_PUBLICSHARE_DIR='$DESK'
XDG_DOCUMENTS_DIR='$DESK'
XDG_MUSIC_DIR='$DESK'
XDG_PICTURES_DIR='$DESK'
XDG_VIDEOS_DIR='$DESK'
" > ~/.config/user-dirs.dirs
